version: "3.9"

services:
  rate-redis:
    image: redis:${REDIS_IMAGE_TAG}
    volumes:
      - rate_limit_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
  gateway:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
    networks:
      - gateway
      - auth
      - biz
    depends_on:
      redis:
        condition: service_healthy

networks:
  gateway:
  auth:
    external:
      name: deffie_hellman_network
  biz:
    external:
      name: biz_network

volumes:
  rate_limit_data: