// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: grpc/auth/authpb.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqPQRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce     string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	MessageId uint64 `protobuf:"varint,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
}

func (x *ReqPQRequest) Reset() {
	*x = ReqPQRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_auth_authpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPQRequest) ProtoMessage() {}

func (x *ReqPQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_authpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPQRequest.ProtoReflect.Descriptor instead.
func (*ReqPQRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auth_authpb_proto_rawDescGZIP(), []int{0}
}

func (x *ReqPQRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ReqPQRequest) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type ReqPQResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce       string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce string `protobuf:"bytes,2,opt,name=serverNonce,proto3" json:"serverNonce,omitempty"`
	MessageId   uint64 `protobuf:"varint,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
	P           string `protobuf:"bytes,4,opt,name=p,proto3" json:"p,omitempty"`
	G           uint64 `protobuf:"varint,5,opt,name=g,proto3" json:"g,omitempty"`
}

func (x *ReqPQResponse) Reset() {
	*x = ReqPQResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_auth_authpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPQResponse) ProtoMessage() {}

func (x *ReqPQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_authpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPQResponse.ProtoReflect.Descriptor instead.
func (*ReqPQResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auth_authpb_proto_rawDescGZIP(), []int{1}
}

func (x *ReqPQResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ReqPQResponse) GetServerNonce() string {
	if x != nil {
		return x.ServerNonce
	}
	return ""
}

func (x *ReqPQResponse) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ReqPQResponse) GetP() string {
	if x != nil {
		return x.P
	}
	return ""
}

func (x *ReqPQResponse) GetG() uint64 {
	if x != nil {
		return x.G
	}
	return 0
}

type ReqDHParamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce       string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce string `protobuf:"bytes,2,opt,name=serverNonce,proto3" json:"serverNonce,omitempty"`
	MessageId   uint64 `protobuf:"varint,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
	A           string `protobuf:"bytes,4,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *ReqDHParamsRequest) Reset() {
	*x = ReqDHParamsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_auth_authpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqDHParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDHParamsRequest) ProtoMessage() {}

func (x *ReqDHParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_authpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDHParamsRequest.ProtoReflect.Descriptor instead.
func (*ReqDHParamsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auth_authpb_proto_rawDescGZIP(), []int{2}
}

func (x *ReqDHParamsRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ReqDHParamsRequest) GetServerNonce() string {
	if x != nil {
		return x.ServerNonce
	}
	return ""
}

func (x *ReqDHParamsRequest) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ReqDHParamsRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

type ReqDHParamsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce       string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce string `protobuf:"bytes,2,opt,name=serverNonce,proto3" json:"serverNonce,omitempty"`
	MessageId   uint64 `protobuf:"varint,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
	B           string `protobuf:"bytes,4,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *ReqDHParamsResponse) Reset() {
	*x = ReqDHParamsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_auth_authpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqDHParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDHParamsResponse) ProtoMessage() {}

func (x *ReqDHParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_authpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDHParamsResponse.ProtoReflect.Descriptor instead.
func (*ReqDHParamsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auth_authpb_proto_rawDescGZIP(), []int{3}
}

func (x *ReqDHParamsResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ReqDHParamsResponse) GetServerNonce() string {
	if x != nil {
		return x.ServerNonce
	}
	return ""
}

func (x *ReqDHParamsResponse) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ReqDHParamsResponse) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

var File_grpc_auth_authpb_proto protoreflect.FileDescriptor

var file_grpc_auth_authpb_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x75, 0x74, 0x68, 0x44, 0x48,
	0x22, 0x42, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x50, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x50, 0x51, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x67, 0x22, 0x78, 0x0a, 0x12, 0x72, 0x65, 0x71, 0x44,
	0x48, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f,
	0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x01, 0x61, 0x22, 0x79, 0x0a, 0x13, 0x72, 0x65, 0x71, 0x44, 0x48, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12,
	0x0c, 0x0a, 0x01, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x62, 0x32, 0x8b, 0x01,
	0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a,
	0x05, 0x72, 0x65, 0x71, 0x50, 0x51, 0x12, 0x14, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x44, 0x48, 0x2e,
	0x52, 0x65, 0x71, 0x50, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x44, 0x48, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x51, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x44, 0x48, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x44, 0x48, 0x2e, 0x72, 0x65, 0x71, 0x44,
	0x48, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x44, 0x48, 0x2e, 0x72, 0x65, 0x71, 0x44, 0x48, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_auth_authpb_proto_rawDescOnce sync.Once
	file_grpc_auth_authpb_proto_rawDescData = file_grpc_auth_authpb_proto_rawDesc
)

func file_grpc_auth_authpb_proto_rawDescGZIP() []byte {
	file_grpc_auth_authpb_proto_rawDescOnce.Do(func() {
		file_grpc_auth_authpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_auth_authpb_proto_rawDescData)
	})
	return file_grpc_auth_authpb_proto_rawDescData
}

var file_grpc_auth_authpb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_auth_authpb_proto_goTypes = []interface{}{
	(*ReqPQRequest)(nil),        // 0: authDH.ReqPQRequest
	(*ReqPQResponse)(nil),       // 1: authDH.ReqPQResponse
	(*ReqDHParamsRequest)(nil),  // 2: authDH.reqDHParamsRequest
	(*ReqDHParamsResponse)(nil), // 3: authDH.reqDHParamsResponse
}
var file_grpc_auth_authpb_proto_depIdxs = []int32{
	0, // 0: authDH.AuthService.reqPQ:input_type -> authDH.ReqPQRequest
	2, // 1: authDH.AuthService.reqDHParams:input_type -> authDH.reqDHParamsRequest
	1, // 2: authDH.AuthService.reqPQ:output_type -> authDH.ReqPQResponse
	3, // 3: authDH.AuthService.reqDHParams:output_type -> authDH.reqDHParamsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_auth_authpb_proto_init() }
func file_grpc_auth_authpb_proto_init() {
	if File_grpc_auth_authpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_auth_authpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPQRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_auth_authpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPQResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_auth_authpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqDHParamsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_auth_authpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqDHParamsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_auth_authpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_auth_authpb_proto_goTypes,
		DependencyIndexes: file_grpc_auth_authpb_proto_depIdxs,
		MessageInfos:      file_grpc_auth_authpb_proto_msgTypes,
	}.Build()
	File_grpc_auth_authpb_proto = out.File
	file_grpc_auth_authpb_proto_rawDesc = nil
	file_grpc_auth_authpb_proto_goTypes = nil
	file_grpc_auth_authpb_proto_depIdxs = nil
}
