// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: grpc/auth/authpb.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthService_ReqPQ_FullMethodName       = "/authDH.AuthService/reqPQ"
	AuthService_ReqDHParams_FullMethodName = "/authDH.AuthService/reqDHParams"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	ReqPQ(ctx context.Context, in *ReqPQRequest, opts ...grpc.CallOption) (*ReqPQResponse, error)
	ReqDHParams(ctx context.Context, in *ReqDHParamsRequest, opts ...grpc.CallOption) (*ReqDHParamsResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) ReqPQ(ctx context.Context, in *ReqPQRequest, opts ...grpc.CallOption) (*ReqPQResponse, error) {
	out := new(ReqPQResponse)
	err := c.cc.Invoke(ctx, AuthService_ReqPQ_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ReqDHParams(ctx context.Context, in *ReqDHParamsRequest, opts ...grpc.CallOption) (*ReqDHParamsResponse, error) {
	out := new(ReqDHParamsResponse)
	err := c.cc.Invoke(ctx, AuthService_ReqDHParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	ReqPQ(context.Context, *ReqPQRequest) (*ReqPQResponse, error)
	ReqDHParams(context.Context, *ReqDHParamsRequest) (*ReqDHParamsResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) ReqPQ(context.Context, *ReqPQRequest) (*ReqPQResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqPQ not implemented")
}
func (UnimplementedAuthServiceServer) ReqDHParams(context.Context, *ReqDHParamsRequest) (*ReqDHParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqDHParams not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_ReqPQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ReqPQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ReqPQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ReqPQ(ctx, req.(*ReqPQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ReqDHParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqDHParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ReqDHParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ReqDHParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ReqDHParams(ctx, req.(*ReqDHParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authDH.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "reqPQ",
			Handler:    _AuthService_ReqPQ_Handler,
		},
		{
			MethodName: "reqDHParams",
			Handler:    _AuthService_ReqDHParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/auth/authpb.proto",
}
